/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class JsonUtil */

#ifndef _Included_utils_JsonUtil
#define _Included_utils_JsonUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JsonUtil
 * Method:    notFastParseJson
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT jboolean JNICALL Java_utils_JsonUtil_notFastParseJson
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
